 # Arthematic Operations

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])
b = np.array([5,3,2])

In [3]:
a + b

array([7, 6, 6])

In [4]:
a*b

array([10,  9,  8])

In [5]:
a/b

array([0.4, 1. , 2. ])

In [6]:
a -b

array([-3,  0,  2])

In [7]:
np.add(a,b)

array([7, 6, 6])

In [8]:
np.subtract(a,b)

array([-3,  0,  2])

In [9]:
np.multiply(a,b)

array([10,  9,  8])

In [10]:
np.divide(a,b)

array([0.4, 1. , 2. ])

# Recipocal <which always divide by -1


In [11]:
a

array([2, 3, 4])

In [12]:
np.reciprocal([a])

array([[0, 0, 0]], dtype=int32)

In [13]:
#for d-type
np.reciprocal([2,3,0.4])

array([0.5       , 0.33333333, 2.5       ])

In [14]:
#power
np.power([10,20],2)

array([100, 400], dtype=int32)

In [15]:
np.power([10,20],[2,3])

array([ 100, 8000], dtype=int32)

# Module funtion
divide by one number into another


In [16]:
np.mod([10,20,30],7)

array([3, 6, 2], dtype=int32)

In [17]:
np.mod([10,20,30],[2,3,5])

array([0, 2, 0], dtype=int32)