# Array_Manipulation

In [1]:
import numpy as np

In [2]:
# 1_dimensional
d_1 = np.array([1,2,3])
print(d_1)

[1 2 3]


In [3]:
# 2_dimensional
d_2 = np.array([[1,2,3],[4,5,6]])
print(d_2)

[[1 2 3]
 [4 5 6]]


In [4]:
# 3_dimensional
d_3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(d_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


### shape of the columns

In [5]:
d_1.shape #1_row,1_column

(3,)

In [6]:
d_2.shape #2_row,3_column

(2, 3)

In [7]:
d_3.shape #hole value,3_rows,3_columns

(1, 3, 3)

### length of the functions

In [8]:
len(d_1)
len(d_2)
len(d_3)

1

### checking elements

In [9]:
d_1.size

3

In [10]:
d_2.size

6

In [11]:
d_3.size

9

### Data types

In [12]:
d_1.dtype

dtype('int32')

In [13]:
d_2.dtype

dtype('int32')

In [14]:
d_3.dtype

dtype('int32')

In [15]:
np.array([[1,2,3],[4,-5.0,6.6]]).dtype

dtype('float64')

### To check dimensionals

In [16]:
d_1.ndim

1

In [17]:
d_2.ndim

2

In [18]:
d_3.ndim

3

In [19]:
d_1.ndim,d_2.ndim,d_3.ndim

(1, 2, 3)

### array manipulation

In [20]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [21]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [22]:
b = a.reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

### flatten function

In [23]:
# it will convert our high end data to 1_dimensional
b.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [24]:
# iteration
for ele in b.flatten():
    print(ele)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


### flatten()==ravel()

In [25]:
b.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [26]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [27]:
# changing tabel dimensions
b.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [28]:
# to print "column" continuation in 1_dimension
b.ravel('c')

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [29]:
# to print "row" continuation in 1_d
b.ravel('f')

array([ 0,  6, 12, 18, 24,  1,  7, 13, 19, 25,  2,  8, 14, 20, 26,  3,  9,
       15, 21, 27,  4, 10, 16, 22, 28,  5, 11, 17, 23, 29])

In [30]:
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [31]:
# transpose
b.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

***

# Concatination

In [32]:
c = np.array([[1,2],[3,4]])
d = np.array([[5,6],[7,8]])

In [33]:
print(c),print(d)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


(None, None)

In [34]:
np.concatenate((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [35]:
# concatenate == vstack
np.vstack((c,d))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
# to display in horizontal
np.hstack((c,d))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### Splitting

In [37]:
f = np.arange(10)
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
np.split(f,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [39]:
# 2_dimensional
z = np.arange(16).reshape(4,4)
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [40]:
# horzontal split
np.hsplit(z,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [41]:
# vertical split
np.vsplit(z,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

### Append

In [42]:
#addding any two number to elements
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
np.append(f,23)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 23])

In [44]:
z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [45]:
np.append(z,[100,1010,102])

array([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,   10,
         11,   12,   13,   14,   15,  100, 1010,  102])

In [46]:
np.append(z,[[21,31,41,51]], axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [21, 31, 41, 51]])

In [47]:
# insert particuar variable
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.insert(f,5,100)

array([  0,   1,   2,   3,   4, 100,   5,   6,   7,   8,   9])

### Delete cell

In [49]:
f

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
np.delete(f,8)

array([0, 1, 2, 3, 4, 5, 6, 7, 9])

***

### Arange function

In [51]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
np.arange(-10,10,5)

array([-10,  -5,   0,   5])

### Line space = np.linspace(start,end,divisible number)

In [54]:
np.linspace(0,10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [55]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [56]:
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

### Logspace(start,end,divide)

In [57]:
np.logspace(0,10)

array([1.00000000e+00, 1.59985872e+00, 2.55954792e+00, 4.09491506e+00,
       6.55128557e+00, 1.04811313e+01, 1.67683294e+01, 2.68269580e+01,
       4.29193426e+01, 6.86648845e+01, 1.09854114e+02, 1.75751062e+02,
       2.81176870e+02, 4.49843267e+02, 7.19685673e+02, 1.15139540e+03,
       1.84206997e+03, 2.94705170e+03, 4.71486636e+03, 7.54312006e+03,
       1.20679264e+04, 1.93069773e+04, 3.08884360e+04, 4.94171336e+04,
       7.90604321e+04, 1.26485522e+05, 2.02358965e+05, 3.23745754e+05,
       5.17947468e+05, 8.28642773e+05, 1.32571137e+06, 2.12095089e+06,
       3.39322177e+06, 5.42867544e+06, 8.68511374e+06, 1.38949549e+07,
       2.22299648e+07, 3.55648031e+07, 5.68986603e+07, 9.10298178e+07,
       1.45634848e+08, 2.32995181e+08, 3.72759372e+08, 5.96362332e+08,
       9.54095476e+08, 1.52641797e+09, 2.44205309e+09, 3.90693994e+09,
       6.25055193e+09, 1.00000000e+10])

In [58]:
np.logspace(0,10,3)

array([1.e+00, 1.e+05, 1.e+10])

In [59]:
np.logspace(1,10,2)

array([1.e+01, 1.e+10])

### Base genrating
### np.logspace(start,end,num=divisble,base=number)

In [60]:
np.logspace(1,10,num=2,base=2)

array([   2., 1024.])

In [61]:
np.logspace(1,10,num=10,base=2)

array([   2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.,
       1024.])

### Zeros

In [62]:
np.zeros(3) #1_d

array([0., 0., 0.])

In [63]:
np.zeros((3,5)) #2_d

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [64]:
np.zeros(((3,3,3))) #3_d

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [65]:
np.ones(3)

array([1., 1., 1.])

In [66]:
np.ones(((3,4,5)))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

### filling same matrix

In [67]:
# np.full((row,coloum),fill up num=x)
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

### Diagonal element

In [68]:
#np.eye(number)
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### Empty matrix

In [70]:
#np.empty(row,coloum)
np.empty((3,6))

array([[6.18566960e-312, 5.53353523e-322, 0.00000000e+000,
        0.00000000e+000, 1.33511018e-306, 1.15998412e-028],
       [2.44171989e+232, 8.00801729e+159, 7.06269593e-077,
        2.99067252e-067, 1.28448408e-057, 5.51681714e-048],
       [2.36945494e-038, 4.40610747e-062, 3.77780862e+180,
        1.15998412e-028, 6.48224638e+170, 3.67145870e+228]])

***

# Array Broadcasting
#### When ever we do two arthematic operations with two diffrent set then the result how numpy reacts is called 'Broad casting'

In [71]:
x = np.array([1,2,3])
y = np.array([3,4,5])

In [72]:
x,y

(array([1, 2, 3]), array([3, 4, 5]))

In [73]:
x+y

array([4, 6, 8])

In [74]:
c = np.arange(12).reshape(4,3)
d = np.array([3,4,5])

In [75]:
c,d

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([3, 4, 5]))

In [76]:
c+d

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [77]:
c*d

array([[ 0,  4, 10],
       [ 9, 16, 25],
       [18, 28, 40],
       [27, 40, 55]])

In [78]:
c/d

array([[0.  , 0.25, 0.4 ],
       [1.  , 1.  , 1.  ],
       [2.  , 1.75, 1.6 ],
       [3.  , 2.5 , 2.2 ]])

# Iterating array
#### your are trying out every single element inarray.Which is not inbuilt in the nuppy array "for-loop" is used for iterating array.
### for ele in np.nditer(variable):

In [79]:
e = np.array([2,4,5])

In [80]:
for ele in np.nditer(e):
    print(ele)

2
4
5


In [81]:
f = np.arange(0,1000,5)

In [82]:
for ele in np.nditer(f):
    print(ele)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995


In [83]:
for ele in np.nditer(f):
    print(ele+3)

3
8
13
18
23
28
33
38
43
48
53
58
63
68
73
78
83
88
93
98
103
108
113
118
123
128
133
138
143
148
153
158
163
168
173
178
183
188
193
198
203
208
213
218
223
228
233
238
243
248
253
258
263
268
273
278
283
288
293
298
303
308
313
318
323
328
333
338
343
348
353
358
363
368
373
378
383
388
393
398
403
408
413
418
423
428
433
438
443
448
453
458
463
468
473
478
483
488
493
498
503
508
513
518
523
528
533
538
543
548
553
558
563
568
573
578
583
588
593
598
603
608
613
618
623
628
633
638
643
648
653
658
663
668
673
678
683
688
693
698
703
708
713
718
723
728
733
738
743
748
753
758
763
768
773
778
783
788
793
798
803
808
813
818
823
828
833
838
843
848
853
858
863
868
873
878
883
888
893
898
903
908
913
918
923
928
933
938
943
948
953
958
963
968
973
978
983
988
993
998


In [84]:
for ele in np.nditer(e):
    print(ele/5)

0.4
0.8
1.0


In [85]:
for ele in np.nditer(e):
    print(ele/3)

0.6666666666666666
1.3333333333333333
1.6666666666666667


## Arthematic Operation

In [86]:
j = np.array([2,3,4])
f = np.array([5,6,7])

In [87]:
j+f

array([ 7,  9, 11])

In [88]:
j*f

array([10, 18, 28])

In [89]:
j/f

array([0.4       , 0.5       , 0.57142857])

In [90]:
j - f

array([-3, -3, -3])

In [91]:
np.add(j,f)

array([ 7,  9, 11])

In [92]:
np.subtract(j,f)

array([-3, -3, -3])

In [93]:
np.multiply(j,f)

array([10, 18, 28])

In [94]:
np.divide(j,f)

array([0.4       , 0.5       , 0.57142857])

### Recipocal <which is always divide by -1

In [95]:
j

array([2, 3, 4])

In [96]:
np.reciprocal([j])

array([[0, 0, 0]], dtype=int32)

In [97]:
np.reciprocal([2,3,0.4])

array([0.5       , 0.33333333, 2.5       ])

In [98]:
np.power([10,20],2)

array([100, 400], dtype=int32)

### Module function
#### divide by one number into another

In [99]:
np.mod([10,20,30],7)

array([3, 6, 2], dtype=int32)

In [100]:
np.mod([10,20,30],[2,3,5])

array([0, 2, 0], dtype=int32)

***

# Statistical Function

In [101]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [102]:
#maximum value
np.amax(a)

15

In [103]:
#colmun max
np.amax(a,axis=0)

array([12, 13, 14, 15])

In [104]:
#row maximum
np.amax(a,axis=1)

array([ 3,  7, 11, 15])

In [105]:
#eqivalent function
np.amin(a)

0

In [106]:
np.amin(a,axis=0)

array([0, 1, 2, 3])

In [107]:
np.amin(a,axis=1)

array([ 0,  4,  8, 12])

### The diffrence b/w min value and maximumvalue

In [108]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
np.mean(a)

7.5

In [110]:
np.ptp(a)

15

In [111]:
np.mean(a,axis=0)

array([6., 7., 8., 9.])

In [112]:
np.mean(a,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [113]:
#median== middle value
np.median(a)

7.5

In [114]:
np.median(a,axis=0)

array([6., 7., 8., 9.])

In [115]:
np.median(a,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

#### Percentail

In [116]:
#np.percentai(variable,how much percentage to be caliculated)
np.percentile(a,50)

7.5

In [117]:
np.percentile(a,25)

3.75

#### Caliculating Standard devation

In [118]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [119]:
np.std(a)

4.6097722286464435

#### Variance is the square of "std"

In [120]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [121]:
np.var(a)

21.25

***

# Mathamatical functions

In [122]:
np.pi

3.141592653589793

In [123]:
#converting radian value to degree
np.degrees(np.pi)

180.0

In [124]:
# converting degrees to radians
np.deg2rad(180)

3.141592653589793

### Trignometry function

In [125]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [126]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [127]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029,  0.75390225],
       [-0.14550003, -0.91113026, -0.83907153,  0.0044257 ],
       [ 0.84385396,  0.90744678,  0.13673722, -0.75968791]])

In [128]:
np.tan(a)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01],
       [ 1.15782128e+00, -3.38051501e+00, -2.91006191e-01,
         8.71447983e-01],
       [-6.79971146e+00, -4.52315659e-01,  6.48360827e-01,
        -2.25950846e+02],
       [-6.35859929e-01,  4.63021133e-01,  7.24460662e+00,
        -8.55993401e-01]])

### Inverse function

In [129]:
x

array([0, 1, 2, 3, 4])

In [130]:
np.arcsin(x)

<ipython-input-130-a6357a09db4c>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(x)


array([0.        , 1.57079633,        nan,        nan,        nan])

In [131]:
np.arccos(a)

<ipython-input-131-d36a14897903>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(a)


array([[1.57079633, 0.        ,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan],
       [       nan,        nan,        nan,        nan]])

In [132]:
np.arctan(a)

array([[0.        , 0.78539816, 1.10714872, 1.24904577],
       [1.32581766, 1.37340077, 1.40564765, 1.42889927],
       [1.44644133, 1.46013911, 1.47112767, 1.48013644],
       [1.48765509, 1.49402444, 1.49948886, 1.50422816]])

### Hyperbolic

In [133]:
x

array([0, 1, 2, 3, 4])

In [134]:
np.arcsinh(x)

array([0.        , 0.88137359, 1.44363548, 1.81844646, 2.09471255])

In [135]:
np.arccosh(x)

<ipython-input-135-874a41cc42cc>:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(x)


array([       nan, 0.        , 1.3169579 , 1.76274717, 2.06343707])

In [136]:
np.arctanh(a)

<ipython-input-136-f3c4d45a4462>:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(a)
<ipython-input-136-f3c4d45a4462>:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(a)


array([[ 0., inf, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan],
       [nan, nan, nan, nan]])

#### Round values

In [137]:
np.round(5.4)

5.0

In [138]:
np.round(4.9)

5.0

#### Ceil

In [139]:
np.ceil(3.4)

4.0

In [140]:
np.ceil(4.9)

5.0

In [141]:
np.ceil(4.5)

5.0

#### Floor

In [142]:
np.floor(3.2)

3.0

#### Absolute value

In [143]:
np.abs(-5)

5

In [144]:
np.abs(5)

5

***

# Identifiers

In [145]:
y = np.array([2,3,4])
y

array([2, 3, 4])

In [146]:
#if we want to fimd the adress or memory location
id(y)

1252063634320

In [147]:
g = y

In [148]:
id(g)
#This means same adress our data will be stored 
#if we want to change any number and it will display same number
#this means there is no storage in that location

1252063634320

In [149]:
y[0] = -5

In [150]:
y,g

(array([-5,  3,  4]), array([-5,  3,  4]))

### View

In [151]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [152]:
id(a)

1252064038704

In [153]:
b = a.view() # Two diffrent memory location for same array

In [154]:
id(b) 

1252064066704

In [155]:
a[0] = -5

In [156]:
a,b #whenever you change the array it will effect to same array

(array([-5,  3,  4]), array([-5,  3,  4]))

### Copy

In [157]:
h = np.array([2,3,4])

In [158]:
id(h)

1252064063632

In [159]:
k = h.copy()

In [160]:
id(k)

1252064037456

In [161]:
k[1] =400 

In [162]:
h,k  # it doesnt effect to another array

(array([2, 3, 4]), array([  2, 400,   4]))