# Array Broadcasting
#when ever we do two arthamtic operations with two diffrent set then result how numpy reacts is called 'Broad casting'

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([3,4,5])


In [3]:
a,b

(array([1, 2, 3]), array([3, 4, 5]))

In [4]:
a+b

array([4, 6, 8])

In [5]:
#same arthimatic on diffrent sets
c = np.arange(12).reshape(4,3)
d = np.array([3,4,5])

In [6]:
c,d

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([3, 4, 5]))

In [7]:
c + d

array([[ 3,  5,  7],
       [ 6,  8, 10],
       [ 9, 11, 13],
       [12, 14, 16]])

In [8]:
c * d

array([[ 0,  4, 10],
       [ 9, 16, 25],
       [18, 28, 40],
       [27, 40, 55]])

In [9]:
c,d

(array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([3, 4, 5]))

In [10]:
c/d

array([[0.  , 0.25, 0.4 ],
       [1.  , 1.  , 1.  ],
       [2.  , 1.75, 1.6 ],
       [3.  , 2.5 , 2.2 ]])

# Iterating array
#your are trying to walk through out every single element in array.
#which is not inbuilt in the numpy array
#for-loop is used for iterating array
# syn : for ele in np.nditer(variable):
                                   print(ele)


In [11]:
e  = np.array([2,4,5])

In [12]:
for ele in np.nditer(e):
    print(ele)

2
4
5


In [13]:
f = np.arange(0,1000,5)

In [14]:
for ele in np.nditer(f):
    print(ele)

0
5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100
105
110
115
120
125
130
135
140
145
150
155
160
165
170
175
180
185
190
195
200
205
210
215
220
225
230
235
240
245
250
255
260
265
270
275
280
285
290
295
300
305
310
315
320
325
330
335
340
345
350
355
360
365
370
375
380
385
390
395
400
405
410
415
420
425
430
435
440
445
450
455
460
465
470
475
480
485
490
495
500
505
510
515
520
525
530
535
540
545
550
555
560
565
570
575
580
585
590
595
600
605
610
615
620
625
630
635
640
645
650
655
660
665
670
675
680
685
690
695
700
705
710
715
720
725
730
735
740
745
750
755
760
765
770
775
780
785
790
795
800
805
810
815
820
825
830
835
840
845
850
855
860
865
870
875
880
885
890
895
900
905
910
915
920
925
930
935
940
945
950
955
960
965
970
975
980
985
990
995


In [15]:
for ele in np.nditer(f):
    print(ele+3)

3
8
13
18
23
28
33
38
43
48
53
58
63
68
73
78
83
88
93
98
103
108
113
118
123
128
133
138
143
148
153
158
163
168
173
178
183
188
193
198
203
208
213
218
223
228
233
238
243
248
253
258
263
268
273
278
283
288
293
298
303
308
313
318
323
328
333
338
343
348
353
358
363
368
373
378
383
388
393
398
403
408
413
418
423
428
433
438
443
448
453
458
463
468
473
478
483
488
493
498
503
508
513
518
523
528
533
538
543
548
553
558
563
568
573
578
583
588
593
598
603
608
613
618
623
628
633
638
643
648
653
658
663
668
673
678
683
688
693
698
703
708
713
718
723
728
733
738
743
748
753
758
763
768
773
778
783
788
793
798
803
808
813
818
823
828
833
838
843
848
853
858
863
868
873
878
883
888
893
898
903
908
913
918
923
928
933
938
943
948
953
958
963
968
973
978
983
988
993
998


In [16]:
for ele in np.nditer(e):
    print(ele/5)

0.4
0.8
1.0


In [17]:
for ele in np.nditer(e):
    print(ele/3)

0.6666666666666666
1.3333333333333333
1.6666666666666667
