# Identifiers

In [1]:
import numpy as np

In [2]:
a = np.array([2,3,4])

In [3]:
#if we want to find the adrees or memory location

In [4]:
id(a)

2415883752528

In [5]:
b = a

In [6]:
id(b)

2415883752528

In [7]:
#this means same adree our data will be stored
#if we want to change any number and it will display same number.
#this means ther is no storage in that location

In [8]:
a[0] = -5

In [9]:
a,b

(array([-5,  3,  4]), array([-5,  3,  4]))

In [10]:
#if want to print diffrent array

# view

In [11]:
a = np.array([2,3,4])

In [12]:
id(a)

2415883753200

In [13]:
b = a.view()

In [14]:
id(b)

2415883852368

In [15]:
#two diffrent memory locations for same array

In [16]:
a[0] = -5

In [17]:
a,b

(array([-5,  3,  4]), array([-5,  3,  4]))

In [18]:
#whenever you have to change one array it will affect to the another arrray

# Copy

In [19]:
a = np.array([2,3,4])

In [20]:
id(a)

2415883936560

In [21]:
b = a.copy()

In [22]:
id(b)

2415883938192

In [23]:
a[0] = -5

In [24]:
a,b

(array([-5,  3,  4]), array([2, 3, 4]))

In [25]:
# it does not effected to the another array

In [26]:
b[1] = 400

In [27]:
a,b

(array([-5,  3,  4]), array([  2, 400,   4]))