# Numpy Exerise problem

#1.Given below numpy array.write an expression which will replace all negative values with 1000
  #  .arr=np.array([5,0,-3,9,10,-5,-1])

In [1]:
#replace all negative values with 1000

In [2]:
import numpy as np

In [3]:
arr = np.array([5,0,-3,9,10,-5,-1])

In [4]:
#arr[2] = 1000

In [5]:
#arr

In [6]:
arr = np.array([5,0,-3,9,10,-5,-1])
arr<0

array([False, False,  True, False, False,  True,  True])

In [7]:
arr

array([ 5,  0, -3,  9, 10, -5, -1])

In [8]:
arr<0

array([False, False,  True, False, False,  True,  True])

In [9]:
arr[arr<0]=1000

In [10]:
arr

array([   5,    0, 1000,    9,   10, 1000, 1000])

# 3.Create numpy array values between 1000 and 2000,all numbers
# divisible by 5 but not 15.

In [11]:
for i in range(1000,2000,5):
    if (i % 15 !=0):
        print(i)

1000
1010
1015
1025
1030
1040
1045
1055
1060
1070
1075
1085
1090
1100
1105
1115
1120
1130
1135
1145
1150
1160
1165
1175
1180
1190
1195
1205
1210
1220
1225
1235
1240
1250
1255
1265
1270
1280
1285
1295
1300
1310
1315
1325
1330
1340
1345
1355
1360
1370
1375
1385
1390
1400
1405
1415
1420
1430
1435
1445
1450
1460
1465
1475
1480
1490
1495
1505
1510
1520
1525
1535
1540
1550
1555
1565
1570
1580
1585
1595
1600
1610
1615
1625
1630
1640
1645
1655
1660
1670
1675
1685
1690
1700
1705
1715
1720
1730
1735
1745
1750
1760
1765
1775
1780
1790
1795
1805
1810
1820
1825
1835
1840
1850
1855
1865
1870
1880
1885
1895
1900
1910
1915
1925
1930
1940
1945
1955
1960
1970
1975
1985
1990


In [12]:
arr=np.arange(1000,2000,5)
arr[arr % 15!=0]

array([1000, 1010, 1015, 1025, 1030, 1040, 1045, 1055, 1060, 1070, 1075,
       1085, 1090, 1100, 1105, 1115, 1120, 1130, 1135, 1145, 1150, 1160,
       1165, 1175, 1180, 1190, 1195, 1205, 1210, 1220, 1225, 1235, 1240,
       1250, 1255, 1265, 1270, 1280, 1285, 1295, 1300, 1310, 1315, 1325,
       1330, 1340, 1345, 1355, 1360, 1370, 1375, 1385, 1390, 1400, 1405,
       1415, 1420, 1430, 1435, 1445, 1450, 1460, 1465, 1475, 1480, 1490,
       1495, 1505, 1510, 1520, 1525, 1535, 1540, 1550, 1555, 1565, 1570,
       1580, 1585, 1595, 1600, 1610, 1615, 1625, 1630, 1640, 1645, 1655,
       1660, 1670, 1675, 1685, 1690, 1700, 1705, 1715, 1720, 1730, 1735,
       1745, 1750, 1760, 1765, 1775, 1780, 1790, 1795, 1805, 1810, 1820,
       1825, 1835, 1840, 1850, 1855, 1865, 1870, 1880, 1885, 1895, 1900,
       1910, 1915, 1925, 1930, 1940, 1945, 1955, 1960, 1970, 1975, 1985,
       1990])

# 4.Write a funtion which caliculate std of 1-d array result with inbuilt function
#defcal_std(arr)


In [13]:
a = np.random.normal(0,10,100)
a

array([ -0.74588005,  -6.65308128,  -2.43979153,  -8.09295899,
       -11.09501807,   5.92350906,  10.12307202,   1.56902884,
        -5.6771885 ,   0.76425999,   8.60806148,  28.19033484,
        -5.75874502, -15.27930594,  -8.28412144,  10.32625589,
         1.09407754,  11.15987334,   2.17761187,  -4.77332301,
       -15.81293142,  -7.75445492,   1.90350583,   4.69398421,
       -15.60574195,   3.03029007,   6.53336395,  -1.46731327,
        -8.28937985,  -0.44016339,   9.50116728,  -0.11371762,
         3.62181295,  -3.03922921,   2.23780596,  -3.15886571,
       -18.32298987,  -0.91132135,   7.35845653,   6.84472592,
        30.52387721,   7.04585082,  -0.22230663,  -8.95920988,
        -7.35542754,   6.13989585,   3.94684885,   1.75283716,
       -18.40373139,   4.56861408, -18.05453071,   7.29506178,
       -11.74882793,   1.07119462,   4.05724255,   7.10112505,
        -4.00681845,  12.64287135,   3.28582871,   5.51531914,
        14.04174506,  18.33931701,  -5.54485404,  12.04

In [14]:
np.std(a)

9.237412747883337

In [15]:
#numpy formate
#new function
def cal_std(arr):
    mean = np.mean(a)
    diff = a - mean       #diff= define new value
    square = np.sum(np.power(diff , 2))/len(a) 
    root = np.power(square,0.5)        # 0.5 is the exponent
    return root

In [16]:
cal_std(a)

9.237412747883337