# Numpy index & slicing

In [1]:
import numpy as np

#one-dimensinol indexing<every single value assosiated with some potive number is called indexing>
#if we want select perticular number indexing is used its starts from 'zero'
    # synta:variable = [lowerrange : upperrange]


In [2]:
a = np.arange(5,20)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [3]:
a[5]

10

In [4]:
a[0]

5

In [5]:
a[3:9]

array([ 8,  9, 10, 11, 12, 13])

In [6]:
a[-1]

19

In [7]:
a[:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
a[-5:]

array([15, 16, 17, 18, 19])

In [9]:
a[4:]

array([ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [10]:
a[4:8]

array([ 9, 10, 11, 12])

In [11]:
a[-5:-1]

array([15, 16, 17, 18])

# 2-dimensional indexing
#syntax:variable = np.arange(start,end).reshape(row,coloum)

In [12]:
b = np.arange(50,75).reshape(5,5)
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [13]:
#row-indexing
b[0]

array([50, 51, 52, 53, 54])

In [14]:
b[2:3]

array([[60, 61, 62, 63, 64]])

In [15]:
b[1:4]

array([[55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69]])

In [16]:
b[:1]

array([[50, 51, 52, 53, 54]])

In [17]:
#coloum-indexing
#syntax:varaible[row-(start,end), coloum-(start,end)]

In [18]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [19]:
b[:,0]

array([50, 55, 60, 65, 70])

In [20]:
b[:,0:3]

array([[50, 51, 52],
       [55, 56, 57],
       [60, 61, 62],
       [65, 66, 67],
       [70, 71, 72]])

In [21]:
#range of coloum
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [22]:
b[[0,4]]

array([[50, 51, 52, 53, 54],
       [70, 71, 72, 73, 74]])

In [23]:
b[[4,1]]

array([[70, 71, 72, 73, 74],
       [55, 56, 57, 58, 59]])

In [24]:
#coloum-range
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [25]:
b[:,[0,4]]

array([[50, 54],
       [55, 59],
       [60, 64],
       [65, 69],
       [70, 74]])

In [26]:
b[:,[4,0]]

array([[54, 50],
       [59, 55],
       [64, 60],
       [69, 65],
       [74, 70]])

In [27]:
b[:,[1,3]]

array([[51, 53],
       [56, 58],
       [61, 63],
       [66, 68],
       [71, 73]])

In [28]:
#range:row-particular
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [29]:
b[1,2:]

array([57, 58, 59])

In [30]:
b[3,2]

67

In [31]:
b[3,4]

69

In [32]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [33]:
b[1:3,2:3]

array([[57],
       [62]])

In [34]:
b[1:4,2:4]

array([[57, 58],
       [62, 63],
       [67, 68]])

In [35]:
b[0:4,2:4]

array([[52, 53],
       [57, 58],
       [62, 63],
       [67, 68]])

In [36]:
#particular number in row-coloum
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [37]:
b[1:3,[2,4]]

array([[57, 59],
       [62, 64]])

In [38]:
b[[1,3],[2,4]]

array([57, 69])

# bollen -indexing

In [39]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [40]:
a>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [41]:
mask = a>10
a[mask]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [42]:
a==5

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [43]:
a[a==5]

array([5])