# Indexing & Slicing

# 1- dimensional

In [1]:
import numpy as np

In [2]:
a = np.arange(5,20)

In [3]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# Selecting particular cell in 1_d

In [4]:
a[0]

5

In [5]:
a[10]

15

In [6]:
a[3:] #from 3rd column to print entire values

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
a[7:9] # to print particular range

array([12, 13])

In [8]:
a[:]  # to print entire column

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [9]:
a[-1] #to select from reverse

19

In [10]:
a[-3:]

array([17, 18, 19])

In [11]:
a[-9:-5]  #to print particular range from reverse
          # a[-end : -start]

array([11, 12, 13, 14])

In [12]:
a[-10:-4]

array([10, 11, 12, 13, 14, 15])

In [13]:
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
# to dselect particular number from single indexing?

***

# 2_d indexing

In [15]:
np.arange(50,75)

array([50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66,
       67, 68, 69, 70, 71, 72, 73, 74])

In [16]:
np.arange(50,75).reshape(5,5)

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [17]:
b = np.arange(50,75).reshape(5,5)

### row_displaying

In [18]:
b[0]

array([50, 51, 52, 53, 54])

In [19]:
b[0:3] 

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

In [20]:
b[3:4] #selecting particular row

array([[65, 66, 67, 68, 69]])

In [21]:
b[:1]

array([[50, 51, 52, 53, 54]])

In [22]:
b[:3]

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

### Column indexing

In [23]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [24]:
b[:,0] # ":" start to end

array([50, 55, 60, 65, 70])

In [25]:
b[:,3]

array([53, 58, 63, 68, 73])

In [26]:
b[:,0:3] # to select from a particular start to particular end

array([[50, 51, 52],
       [55, 56, 57],
       [60, 61, 62],
       [65, 66, 67],
       [70, 71, 72]])

In [27]:
b[:,2:4]

array([[52, 53],
       [57, 58],
       [62, 63],
       [67, 68],
       [72, 73]])

### Selecting from particular rows and columns

In [28]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [29]:
b[1:3,1:3] #b[row_1 start : row_2 end , column_1 start : column_2 end]

array([[56, 57],
       [61, 62]])

In [30]:
b[2:4,3:] 

array([[63, 64],
       [68, 69]])

In [31]:
b[3:,2:4]

array([[67, 68],
       [72, 73]])

In [32]:
b[:2,3:]

array([[53, 54],
       [58, 59]])

In [33]:
b[1,0] # to select "55" b[row : column]

55

In [34]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [35]:
b[3,3:4]  # to select '68' b[row,column_1 start : column_2 end]

array([68])

In [36]:
b[4,4]

74

In [37]:
b[2:4,3:4]

array([[63],
       [68]])

In [38]:
b[4,0:2]

array([70, 71])

In [39]:
b[2,2:4]

array([62, 63])

***

## To select multiple rows

In [40]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [41]:
b[0] # to select single column we use single "Braces"

array([50, 51, 52, 53, 54])

In [42]:
b[[1,3]] # to select multiple columns we use "2_braces"

array([[55, 56, 57, 58, 59],
       [65, 66, 67, 68, 69]])

In [43]:
b[[0,4]]

array([[50, 51, 52, 53, 54],
       [70, 71, 72, 73, 74]])

### to select multile columns

In [44]:
b[:]

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [45]:
b[:,0]  # it displays in vertical

array([50, 55, 60, 65, 70])

In [46]:
b[:,[0]]  # it displays in vertical

array([[50],
       [55],
       [60],
       [65],
       [70]])

In [47]:
b[:,[0,4]]

array([[50, 54],
       [55, 59],
       [60, 64],
       [65, 69],
       [70, 74]])

In [48]:
b[:,0:2]

array([[50, 51],
       [55, 56],
       [60, 61],
       [65, 66],
       [70, 71]])

In [49]:
b[:,[1,3]]

array([[51, 53],
       [56, 58],
       [61, 63],
       [66, 68],
       [71, 73]])

In [50]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [51]:
b[:,[4,1]]

array([[54, 51],
       [59, 56],
       [64, 61],
       [69, 66],
       [74, 71]])

In [52]:
b[1,2:]

array([57, 58, 59])

In [53]:
b[1:4,2:4]   #b[row_1 start : row_2 end ,column_1 start : column_2 end]

array([[57, 58],
       [62, 63],
       [67, 68]])

In [54]:
b[1:3,2:3]

array([[57],
       [62]])

In [55]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [56]:
c = b[:,[4,0]]

In [57]:
c

array([[54, 50],
       [59, 55],
       [64, 60],
       [69, 65],
       [74, 70]])

In [58]:
c[2:4,:]

array([[64, 60],
       [69, 65]])

In [59]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [60]:
b[3:4,3:4]

array([[68]])

### selceting diffrent numbers from diffrent rows

In [61]:
b

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74]])

In [62]:
b[1:3]

array([[55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64]])

In [63]:
b[1:3,[2,4]]

array([[57, 59],
       [62, 64]])

In [64]:
b[3:,[4,1]]

array([[69, 66],
       [74, 71]])

In [65]:
b[1:3,[3,0]]  # b[row_1 : row_2,[column_1,column2]]

array([[58, 55],
       [63, 60]])

In [66]:
b[3:,[4,2,0]]

array([[69, 67, 65],
       [74, 72, 70]])

***

# Bollen_Indexing

In [67]:
c = np.arange(5,20)

In [68]:
c

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [69]:
c>10

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [70]:
amj = c>10 # to store in a variable it display values

In [71]:
c[amj]

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

In [72]:
c==5

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [73]:
c[c==5]

array([5])

***

# Data Types

In [74]:
list = [1,2,3]

In [75]:
list

[1, 2, 3]

In [76]:
d_1 = np.array(list)

In [77]:
d_1

array([1, 2, 3])

In [78]:
type(d_1) # to check the data type

numpy.ndarray

### 2d_array

In [79]:
d_2 = np.array([[1,2,3],[4,5,6]])  #list within a list

In [80]:
d_2

array([[1, 2, 3],
       [4, 5, 6]])

In [81]:
type(d_2)

numpy.ndarray

In [82]:
d_3 = np.array([[1,2,3],[3,4,5],[6,7,8]])

In [83]:
d_3

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [84]:
type(d_3)

numpy.ndarray

### Float

In [85]:
np.array([[1,2,3],[4,5,-6.0]])

array([[ 1.,  2.,  3.],
       [ 4.,  5., -6.]])

***

## Explicit Argument

In [86]:
np.array([[0,1,2],[-3,4,5]],dtype=np.float_)

array([[ 0.,  1.,  2.],
       [-3.,  4.,  5.]])

In [87]:
np.array([[0,1,2],[-3,4,5]],dtype=np.complex_)

array([[ 0.+0.j,  1.+0.j,  2.+0.j],
       [-3.+0.j,  4.+0.j,  5.+0.j]])

In [88]:
np.array([[0,1,2],[-3,4,5]],dtype=np.bool_)

array([[False,  True,  True],
       [ True,  True,  True]])

### Non-homogenius element

In [89]:
np.array(['amjad',True,23,6.6])

array(['amjad', 'True', '23', '6.6'], dtype='<U32')