# Linear Algebra

In [1]:
import numpy as np

In [2]:
a =np.array([[2,5,7],
             [0,9,7],
             [1,-5,8]])

In [3]:
#to identify the rank matrix.
np.linalg.matrix_rank(a)

3

In [4]:
#addition of submition of all those elements,will be identify by using
#it will add diagonal elements
#it will be dedut in the core only
np.trace(a)

19

# Square Matrix-Determinent

In [5]:
#to go inside the module.
np.linalg.det(a)

186.00000000000009

# Inverse function


In [6]:
np.linalg.inv(a)

array([[ 0.57526882, -0.40322581, -0.15053763],
       [ 0.03763441,  0.0483871 , -0.07526882],
       [-0.0483871 ,  0.08064516,  0.09677419]])

# The power the of the matrix

In [7]:
np.linalg.matrix_power(a,3)

array([[ 127, -290, 1057],
       [ 133, -146, 1323],
       [  56, -850, -202]])

# Eigen- value

In [8]:
np.linalg.eig(a)

(array([1.80701898+0.j        , 8.59649051+5.38816368j,
        8.59649051-5.38816368j]),
 array([[ 0.99213348+0.j        , -0.54097002-0.09822029j,
         -0.54097002+0.09822029j],
        [ 0.08730715+0.j        , -0.66121678+0.j        ,
         -0.66121678-0.j        ],
        [-0.0897141 +0.j        ,  0.03811532-0.50896346j,
          0.03811532+0.50896346j]]))

In [9]:
#decompostion of orginal matrix into three diffrent matrix

In [10]:
np.linalg.svd(a)

(array([[-0.60628635,  0.03765492, -0.79435444],
        [-0.75847232, -0.32761986,  0.56336931],
        [-0.23903266,  0.94405897,  0.22719166]]),
 array([14.44319001,  9.35408353,  1.37672937]),
 array([[-0.10050448, -0.59976496, -0.7938393 ],
        [ 0.10897581, -0.79971479,  0.59040709],
        [-0.98895052, -0.02717072,  0.14573479]]))

# linear equation



In [11]:
#problem
#x + y = 5
#2x - 5y = 10

In [12]:
a = np.array([[1,1,],[2,-5]])

In [13]:
b = np.array([5,10])

In [14]:
np.linalg.solve(a,b)

array([5., 0.])