# Mathematical Functions

In [1]:
import numpy as np

In [2]:
np.pi

3.141592653589793

In [3]:
#radian valur to digree
np.degrees(np.pi)

180.0

In [4]:
#degree to radian
np.deg2rad(180)

3.141592653589793

# Trignometry funtions

In [5]:
a = np.arange(5)

In [6]:
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [7]:
np.cos(a)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [8]:
np.tan(a)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128])

# inverse functions

In [9]:
a

array([0, 1, 2, 3, 4])

In [10]:
np.arcsin(a)

<ipython-input-10-1344fc335193>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(a)


array([0.        , 1.57079633,        nan,        nan,        nan])

In [11]:
np.arccos(a)

<ipython-input-11-d36a14897903>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(a)


array([1.57079633, 0.        ,        nan,        nan,        nan])

In [12]:
np.arctan(a)

array([0.        , 0.78539816, 1.10714872, 1.24904577, 1.32581766])

# Hyper bolic 

In [13]:
a

array([0, 1, 2, 3, 4])

In [14]:
np.arcsinh(a)

array([0.        , 0.88137359, 1.44363548, 1.81844646, 2.09471255])

In [15]:
np.arccosh(a)

<ipython-input-15-1890b126e793>:1: RuntimeWarning: invalid value encountered in arccosh
  np.arccosh(a)


array([       nan, 0.        , 1.3169579 , 1.76274717, 2.06343707])

In [16]:
np.arctanh(a)

<ipython-input-16-f3c4d45a4462>:1: RuntimeWarning: divide by zero encountered in arctanh
  np.arctanh(a)
<ipython-input-16-f3c4d45a4462>:1: RuntimeWarning: invalid value encountered in arctanh
  np.arctanh(a)


array([ 0., inf, nan, nan, nan])

In [17]:
#ronud values
np.round(5.4)

5.0

In [18]:
np.round(4.9)

5.0

In [19]:
np.round(4.5)

4.0

In [20]:
#ceil
np.ceil(3.4)

4.0

In [21]:
np.ceil(4.9)

5.0

In [22]:
np.ceil(4.5)

5.0

In [23]:
#floor
np.floor(3.2)

3.0

In [24]:
#absolute value
np.abs(-5)

5

In [26]:
np.abs(5)

5