# Running Numpy data types

In [1]:
import numpy as np 

## numpy array creation-1
shork key:shift+enter for new cell
##one dimensional array

In [2]:
mylist = [1,2,3]

In [3]:
my_arr_1d = np.array(mylist)

assigh to the variabel

#to check type of array type below line

In [4]:
type(my_arr_1d)

numpy.ndarray

# numpy array -2d
# list within list

In [5]:
my_arr_2d = np.array([[1,2,3],[4,5,6]])

In [6]:
my_arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

# by appling float

In [7]:
np.array([[1,2,3],[4,5,-6.0]])

array([[ 1.,  2.,  3.],
       [ 4.,  5., -6.]])

# explicit argument
# syntax: dtype=np.float,    dtype=np.complex,     dtype=np.bool
# example

In [8]:
np.array([[0,1,2],[-3,4,5]],   dtype=np.float)
np.array([[0,1,2],[-3,4,5]],   dtype=np.complex)
np.array([[0,1,2],[-3,4,5]],   dtype=np.bool)

<ipython-input-8-08eeba8011f2>:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([[0,1,2],[-3,4,5]],   dtype=np.float)
<ipython-input-8-08eeba8011f2>:2: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([[0,1,2],[-3,4,5]],   dtype=np.complex)
<ipython-input-8-08eeba8011f2>:3: DeprecationWarning: `np.bool` is a deprec

array([[False,  True,  True],
       [ True,  True,  True]])

# non-homogenius element-string

In [9]:
np.array(["amjad",True,23,6.6])

array(['amjad', 'True', '23', '6.6'], dtype='<U32')

its a one-dimensional array having uni code value--dtype='<U5'

# 3-dimensional array

In [10]:
my_arr_3d = np.array([[[1,2,],[3,4],[5,6]]])
print(my_arr_3d)

[[[1 2]
  [3 4]
  [5 6]]]
