In [1]:
import numpy as np

In [2]:
np.array([1,2,3],ndmin=2)

array([[1, 2, 3]])

In [3]:
np.array([[1,2,3],[3,4,5]],ndmin=3)

array([[[1, 2, 3],
        [3, 4, 5]]])

In [4]:
np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=30)

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2, 3],
                                   [4, 5, 6],
                                   [7, 8, 9]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [5]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=2)
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
x[0,0]

1

In [7]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]],ndmin=3)
x

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [8]:
x[0,0]

array([1, 2, 3])

In [9]:
# data type consisting of more than one element
x = np.array([(1,2),(3,4)], dtype=[('a','<i4'),('b','<i4')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i4'), ('b', '<i4')])

In [10]:
type(x[0][0])

numpy.int32

In [11]:
x['a']

array([1, 3])

In [12]:
x['b']

array([2, 4])

In [13]:
x = np.array([(1,2),(3,4)], dtype=[('a','<f2'),('b','<i4')])
x

array([(1., 2), (3., 4)], dtype=[('a', '<f2'), ('b', '<i4')])

In [14]:
type(x[0][0])

numpy.float16

In [15]:
x['b']

array([2, 4])

In [16]:
x['a']

array([1., 3.], dtype=float16)

#### creating a array for sub_classes

In [17]:
np.array(np.mat('1 2; 3 4'))

array([[1, 2],
       [3, 4]])

In [18]:
np.array(np.mat('1 2 ; 3 4'),subok=True)

matrix([[1, 2],
        [3, 4]])

### convert the input to anarray

In [19]:
a = np.array([1,2]) #exsisting array are not copied
a

array([1, 2])

In [20]:
np.asarray(a) is a

True

In [21]:
# if dtype is set array is copied only if dtype does not match
a = np.array([1,2],dtype=np.float32)
a

array([1., 2.], dtype=float32)

#### ndarray subclasses are not passed through

In [22]:
issubclass(np.matrix,np.ndarray)

True

In [23]:
a = np.matrix([[1,2]])
a

matrix([[1, 2]])

### numpy.asanyarray

In [24]:
a = [1,2]
b = np.asanyarray(a)
type(b)

numpy.ndarray

In [25]:
a = np.matrix([1,2])
np.asanyarray(a)

matrix([[1, 2]])

In [26]:
#numpy.copy

In [27]:
np.array(a,copy=True)

array([[1, 2]])

create an array x, with a reference y and a copy z:

In [28]:
x = np.array([1,2,3])

In [29]:
y = x
y

array([1, 2, 3])

In [30]:
y[0]

1

In [31]:
y[0] = 10
y

array([10,  2,  3])

In [32]:
x

array([10,  2,  3])

## numpy.fromfunction

In [33]:
#construct an array by executing a function over each condition
np.fromfunction(lambda i, j: i ==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [34]:
np.fromfunction(lambda i, j: i + j,(3,3),dtype =int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [35]:
np.fromfunction(lambda i, j: i + j,(4,4),dtype =int)

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

## Create a new 1_d array from an iterable object

In [36]:
iterable = (x*x for x in range(5))

In [37]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [38]:
for i in range(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [39]:
np.fromiter(range(10),int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.fromiter(iterable, float)

array([], dtype=float64)

## diffrence b/w array & asanyarray

In [41]:
np.array(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
np.asanyarray(list(range(10)))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### A new 1_d array intialized from text data in a string : sep(' ') ,sep(',')

In [43]:
np.fromstring('1 2',dtype=int,sep = ' ')

array([1, 2])

In [44]:
np.fromstring('1, 2',dtype=int,sep=',')

array([1, 2])

## Converting list to array

In [45]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [46]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/class of this object:",type(mat))
print("Here is the matrix\n...\n",mat,"\n........")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimension 2 for a matrix for a vector
print("Size of this matrix: ",mat.size,sep=' ')#size gives the total number of elements
print("Shape of this matrix: ",mat.shape,sep=' ')#shape gives the no of ele along each axes(d)
print("Data type of this matrix: ",mat.dtype,sep=' ')#dtype gives the data type contained in this array

Type/class of this object: <class 'numpy.ndarray'>
Here is the matrix
...
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
........
Dimension of this matrix: 2
Size of this matrix:  9
Shape of this matrix:  (3, 3)
Data type of this matrix:  int32


### Converting Tuples, List to Array

In [47]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ",mat.dtype,sep=' ')#dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarray...")
mat

Data type of the modified matrix:  float64


Even tuples can be converted to ndarray...


array([[1.1, 2. , 3. ],
       [4. , 5.2, 6. ],
       [7. , 8.3, 9. ]])

In [48]:
b = np.array([(1.5,2,3),(4,5,6)])
print("We write b = np.array([(1.5,2,3),(4,5,6)])")
print(b)

We write b = np.array([(1.5,2,3),(4,5,6)])
[[1.5 2.  3. ]
 [4.  5.  6. ]]


## arange and linspace

In [49]:
#list(range(10.34))

In [50]:
np.arange(10.34)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [51]:
print("A series of numbers: ",np.arange(5,16)) # A series of numbers from low to high

A series of numbers:  [ 5  6  7  8  9 10 11 12 13 14 15]


In [52]:
print("Number spaced apart by 2: ",np.arange(0,11,2)) #number spaced apart by 2

Number spaced apart by 2:  [ 0  2  4  6  8 10]


In [53]:
print("Numnber spaced apart by float: ",np.arange(0,11,2.5)) # number spaced apart by 2.5

Numnber spaced apart by float:  [ 0.   2.5  5.   7.5 10. ]


In [54]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [55]:
print("23 linearly spaced number b/w 1 and 5\n...............")
print(np.linspace(1,5,21))

23 linearly spaced number b/w 1 and 5
...............
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


## Matrix creation

In [56]:
print("vector of zeros\n................")
print(np.zeros(50))

vector of zeros
................
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [57]:
print("Matrix of zeros\n.................")
print(np.zeros((3,4)))  #Notice tupels

Matrix of zeros
.................
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [58]:
print("vector of ones\n..............")
print(np.ones(5))

vector of ones
..............
[1. 1. 1. 1. 1.]


In [59]:
print("Matrix of ones\n...............")
print(np.ones((5,2))) #Note matrix dimensions specified by tupels

Matrix of ones
...............
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [60]:
print(np.zeros((3,4,2))) #notice tupels

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


In [61]:
print("vector of matrix\n....................")
print(np.ones((5)))

vector of matrix
....................
[1. 1. 1. 1. 1.]


In [62]:
mat1 = np.eye(4)
print("Identity matrix of dimensions",mat1.shape)
print(mat1)

Identity matrix of dimensions (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [63]:
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [64]:
np.linspace(2.0,3.0,num=5,endpoint=False) # if i dont want 3 in my line space

array([2. , 2.2, 2.4, 2.6, 2.8])

In [65]:
np.linspace(2.0,3.0,num=5,retstep=True)  #if i want seperate distance b/w lines we use

(array([2.  , 2.25, 2.5 , 2.75, 3.  ]), 0.25)

In [66]:
np.linspace(2.0,3.0,num=50,retstep=True)

(array([2.        , 2.02040816, 2.04081633, 2.06122449, 2.08163265,
        2.10204082, 2.12244898, 2.14285714, 2.16326531, 2.18367347,
        2.20408163, 2.2244898 , 2.24489796, 2.26530612, 2.28571429,
        2.30612245, 2.32653061, 2.34693878, 2.36734694, 2.3877551 ,
        2.40816327, 2.42857143, 2.44897959, 2.46938776, 2.48979592,
        2.51020408, 2.53061224, 2.55102041, 2.57142857, 2.59183673,
        2.6122449 , 2.63265306, 2.65306122, 2.67346939, 2.69387755,
        2.71428571, 2.73469388, 2.75510204, 2.7755102 , 2.79591837,
        2.81632653, 2.83673469, 2.85714286, 2.87755102, 2.89795918,
        2.91836735, 2.93877551, 2.95918367, 2.97959184, 3.        ]),
 0.02040816326530612)

## logerthermic(only diff is it gives log values) == linspace

In [67]:
np.logspace(2.0,3.0,num=5)

array([ 100.        ,  177.827941  ,  316.22776602,  562.34132519,
       1000.        ])

In [68]:
np.logspace(2.0,3.0,num=4,endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [69]:
np.logspace(2.0,3.0,num=4,base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

### Extract a diagonal or construct a diagonal array

In [70]:
x = np.arange(9).reshape((3,3))
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [71]:
x.reshape((9,1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [72]:
x = np.arange(9).reshape((3,3,1))
x

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [73]:
x.reshape(-36575,1)  #it will assigh to 9

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [74]:
x = np.arange(9).reshape((3,3))

In [75]:
np.diag(x)

array([0, 4, 8])

In [76]:
np.diag(x, k=1)

array([1, 5])

In [77]:
np.diag(x, k=-1)

array([3, 7])

In [78]:
np.diag(x, k=2)

array([2])

In [79]:
np.diag(np.diag(x))  #diagonal inside a diagonal

array([[0, 0, 0],
       [0, 4, 0],
       [0, 0, 8]])

### Create a two-dimensional array with the flattend input as a diagonal

In [80]:
np.diagflat([[1,2],[3,4]])  #list within a list creating diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [81]:
np.diagflat([1,2],1)  #its represnting k value

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

#### An array with ones at and below the given diagonal and zeros elsewhere

In [82]:
np.tri(3,5,0,dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [83]:
np.tri(3,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [84]:
np.tri(3,5,-1,dtype=int)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0]])

In [85]:
# creating a list in a list  "Lower triangular matrix" if 'k=0'
np.tril(([1,2,3],[4,5,6],[7,8,9],[10,11,12]))

array([[ 1,  0,  0],
       [ 4,  5,  0],
       [ 7,  8,  9],
       [10, 11, 12]])

In [86]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],k=2)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [87]:
np.tril([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],k=1)

array([[ 1,  2,  0],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

### create an upper triangle of an array

In [88]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],k= -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

In [89]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], -1)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 0,  8,  9],
       [ 0,  0, 12]])

## Random number generating

In [90]:
print("Random number generating (from uniform distribution)")
print(np.random.rand(2,3)) #2 by 3 matrix with random number ranging from 0 to 1, note no tuple is necessary

Random number generating (from uniform distribution)
[[0.47539983 0.02368902 0.92408912]
 [0.4058222  0.8655018  0.02831686]]


In [91]:
np.random.rand(2,3,5)

array([[[0.09199664, 0.78256434, 0.09121897, 0.38314113, 0.62408974],
        [0.44482348, 0.87728624, 0.82825792, 0.95549536, 0.39750469],
        [0.55037645, 0.67744222, 0.11233684, 0.37434728, 0.81258074]],

       [[0.59050536, 0.57886073, 0.86659976, 0.94865677, 0.68091598],
        [0.94823313, 0.54637032, 0.80677651, 0.9664482 , 0.14747498],
        [0.44748543, 0.88389955, 0.56239172, 0.28075965, 0.02516039]]])

In [92]:
print("number from Normal distribution with zero and standard devation 1 i.e ,standard normal")
print(np.random.randn(4,3))

number from Normal distribution with zero and standard devation 1 i.e ,standard normal
[[-1.0268856   0.58435408 -0.42341779]
 [ 0.41702773  0.6500723   0.60659218]
 [ 2.49232075  1.12873949  1.37531516]
 [ 0.32376243  0.69795088  0.89022292]]


In [93]:
print("Random integer vector :",np.random.randint(1,100,10)) #randint(low,high,# of samples to be drawn)
print("\nRandom integer matrix")
np.random.randint(1,100,10).reshape(5,2)

Random integer vector : [31 26 58 84 68 77 52 52 80 18]

Random integer matrix


array([[45, 67],
       [99, 80],
       [29, 15],
       [23,  4],
       [ 7, 46]])

In [94]:
print(np.random.randint(1,100,(4,4))) #randint(low,high,# of samplesto be drawn ina tuple to form a matrix)
print("\n20 samples drawn from a dice throw: ",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[24  9 26 36]
 [69 87 61 70]
 [64 65 51 28]
 [36 38  8 31]]

20 samples drawn from a dice throw:  [4 4 6 3 2 6 6 2 2 1 3 1 4 1 6 2 4 3 3 1]


## Reshaping

In [95]:
from numpy .random import randint as ri

In [96]:
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(6,5)

In [97]:
print("shape of a: ",a.shape)
print("shape of b: ",b.shape)
print("shape of c: ",c.shape)

shape of a:  (30,)
shape of b:  (2, 3, 5)
shape of c:  (6, 5)


In [98]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [ 2 70 96 73 42 96  3 73 57 94 74 56 38  6 32  8 90 75 63 62 27 37 65 81
  4  1 39 35 91 35] 
 --------------------

b looks like
 -------------------- 
 [[[ 2 70 96 73 42]
  [96  3 73 57 94]
  [74 56 38  6 32]]

 [[ 8 90 75 63 62]
  [27 37 65 81  4]
  [ 1 39 35 91 35]]] 
 --------------------

c looks like
 -------------------- 
 [[ 2 70 96 73 42]
 [96  3 73 57 94]
 [74 56 38  6 32]
 [ 8 90 75 63 62]
 [27 37 65 81  4]
 [ 1 39 35 91 35]] 
 --------------------


In [99]:
A = ri(1,100,10) #vector of random integer
print("\nvector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A,kind='mergesort'))


vector of random integers
 -------------------------------------------------- 
 [67 84  4 69 72 73 34 62 36 70]

Here is the sorted vector
 -------------------------------------------------- 
 [ 4 34 36 62 67 69 70 72 73 84]


In [100]:
M = ri(1,100,25).reshape(5,5) #matrix of random integers
print("\n5x5 Matrix of random integer\n",'-'*50,"\n",M)
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,kind='mergesort'))
print("\nHere is the sorted matrix along each row\n",'-'*50,"\n",np.sort(M,axis=0,kind='mergesort'))


5x5 Matrix of random integer
 -------------------------------------------------- 
 [[51 28 90 62 33]
 [38 16 92 52 21]
 [20 94 30 80 34]
 [28 30 72 69 18]
 [16 29 88 81 26]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[28 33 51 62 90]
 [16 21 38 52 92]
 [20 30 34 80 94]
 [18 28 30 69 72]
 [16 26 29 81 88]]

Here is the sorted matrix along each row
 -------------------------------------------------- 
 [[16 16 30 52 18]
 [20 28 72 62 21]
 [28 29 88 69 26]
 [38 30 90 80 33]
 [51 94 92 81 34]]


In [101]:
M = ri(1,100,25).reshape(5,5)
M

array([[19, 99, 61, 80, 38],
       [43, 27, 92, 51, 72],
       [66, 70, 49, 55,  1],
       [48, 52, 30, 34, 80],
       [68, 66, 62, 64, 14]])

#### To perform Row wise operations

In [102]:
np.sort(M,kind='mergesort',axis = 0)

array([[19, 27, 30, 34,  1],
       [43, 52, 49, 51, 14],
       [48, 66, 61, 55, 38],
       [66, 70, 62, 64, 72],
       [68, 99, 92, 80, 80]])

In [103]:
a

array([ 2, 70, 96, 73, 42, 96,  3, 73, 57, 94, 74, 56, 38,  6, 32,  8, 90,
       75, 63, 62, 27, 37, 65, 81,  4,  1, 39, 35, 91, 35])

In [104]:
print("Max of a :",a.max())
print("Max of b :",b.max())

Max of a : 96
Max of b : 96


In [105]:
print("Max of a location :",a.argmax()) # it gives location of maximum data "arguments"
print("Max of b location :",b.argmax())
print("Max of c location :",c.argmax())

Max of a location : 2
Max of b location : 2
Max of c location : 2
