# Soarting
#arange in lower level to hiher level


In [1]:
import numpy as np

In [2]:
a = np.array([2,4,8,-5,5,0,-1])

In [3]:
np.sort(a)

array([-5, -1,  0,  2,  4,  5,  8])

In [4]:
a

array([ 2,  4,  8, -5,  5,  0, -1])

In [5]:
#keeps the changed values to perminent
#a = np.sort(a)
#a

In [6]:
a

array([ 2,  4,  8, -5,  5,  0, -1])

# index position
it shows the position of the value

In [7]:
np.argsort(a)

array([3, 6, 5, 0, 1, 4, 2], dtype=int64)

In [8]:
#maximum indexing position value
np.argmax(a)

2

In [9]:
np.argmin(a)

3

In [10]:
a

array([ 2,  4,  8, -5,  5,  0, -1])

In [11]:
#index potion where the values are not zero.
#here the position of the value zero not showing
np.nonzero(a)

(array([0, 1, 2, 3, 4, 6], dtype=int64),)

In [12]:
#index position-it will show
#suppose we want to print particular values which are greater than particulaar number
np.where(a>2)

(array([1, 2, 4], dtype=int64),)

In [13]:
a

array([ 2,  4,  8, -5,  5,  0, -1])

In [14]:
#exact position of the value
#syntax:np.extact(variable>number,particular variable)
np.extract(a>2,a)

array([4, 8, 5])