# statistical Function

In [1]:
import numpy as np

In [2]:
a = np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [3]:
#maximum value
np.amax(a)

15

In [4]:
#coloum max
np.amax(a,axis=0)

array([12, 13, 14, 15])

In [5]:
#row maximum
np.amax(a,axis=1)

array([ 3,  7, 11, 15])

In [6]:
#equvalent function
np.amin(a)

0

In [7]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [8]:
np.amin(a,axis=0)

array([0, 1, 2, 3])

In [9]:
np.amin(a,axis=1)

array([ 0,  4,  8, 12])

# The diffrence betwen min value and maxium value

In [10]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [11]:
np.ptp(a)

15

In [12]:
np.mean(a)

7.5

In [13]:
np.mean(a,axis=0)

array([6., 7., 8., 9.])

In [14]:
np.mean(a,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [15]:
#median = middle value
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [16]:
np.median(a)

7.5

In [17]:
np.median(a,axis=0)

array([6., 7., 8., 9.])

In [18]:
np.median(a,axis=1)

array([ 1.5,  5.5,  9.5, 13.5])

In [19]:
#percentail<np.percentail(varable,how much percentage to be caliculated)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
np.percentile(a,50)

7.5

In [21]:
np.percentile(a,25)

3.75

# caliculating standard devation

In [22]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [23]:
np.std(a)

4.6097722286464435

# variance: is the square of the std

In [24]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [25]:
np.var(a)

21.25